### ISSUE TITLE
UnsetMasterSlave error "The field content is invalid".

### ISSUE THREAD

**Issue by raymessias** [RotherOSS/MasterSlave#5]
When we use the option "Unset Master Ticket" or "Unset Slave Ticket"  in the Action=AgentTicketMasterSlave, the following message appears: "The field content is invalid."

![image](https://github.com/user-attachments/assets/a3b82b1c-6c1d-4141-a476-5fbe7fda73be)
![image](https://github.com/user-attachments/assets/0b1a256b-6a8e-40d9-b5bb-dce0eb5ab505)

The version of OTOBO is 11.0.3, and it is a clean installation with only the ITSM packages installed.
![image](https://github.com/user-attachments/assets/ee8a2a21-c419-47ac-9060-ef52bddf0f48)

**Comment by stefanhaerter** [comment]
Fix is pushed with commit bf9970fad93ffd32821717d64c8526d131794018.
Closing the issue.
